### ISSUE TITLE
Správa pravidel

### ISSUE THREAD

**Issue by kalich5** [skaut/skautis-integration#11]
Jak je tam box "Pravidla"

Bylo by dobré ten odkaz "Pro správu pravidel je nutné se přihlásit do skautISu" aby to nebylo aktivní když není zadané app id. Teď to hází tuhle chybu

`Fatal error: Uncaught Error: Call to a member function getLoginUrl() on null in /data/web/virtuals/70296/virtual/www/subdom/wordpress-test/wp-content/plugins/skautis-integration/src/auth/SkautisLogin.php:54 Stack trace: #0 [internal function]: SkautisIntegration\Auth\SkautisLogin->login() #1 /data/web/virtuals/70296/virtual/www/subdom/wordpress-test/wp-content/plugins/skautis-integration/src/general/Actions.php(93): call_user_func(Array) #2 /data/web/virtuals/70296/virtual/www/subdom/wordpress-test/wp-includes/class-wp-hook.php(298): SkautisIntegration\General\Actions->authActionsRouter(Object(WP_Query)) #3 /data/web/virtuals/70296/virtual/www/subdom/wordpress-test/wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters('', Array) #4 /data/web/virtuals/70296/virtual/www/subdom/wordpress-test/wp-includes/plugin.php(515): WP_Hook->do_action(Array) #5 /data/web/virtuals/70296/virtual/www/subdom/wordpress-test/wp-includes/class-wp-query.php(1683): do_action_ref_array('pre_get_posts', Array) #6 /data/web/virtuals/70296/virt in /data/web/virtuals/70296/virtual/www/subdom/wordpress-test/wp-content/plugins/skautis-integration/src/auth/SkautisLogin.php on line 54`

**Comment by kalich5** [comment]
Tak na Lebedě to neudělá tuhle chybu, když to funguje. Ale vypíšeto to chybu HTTP ERROR 500. Možná by bylo dobré, to mít neaktivní (všude kde takové odkazy jsou), dokud není zadané a uložené APP ID
