### ISSUE TITLE
Chyba pravidel

### ISSUE THREAD

**Issue by kalich5** [skaut/skautis-integration#56]
Fatal error: Uncaught Error: Cannot use object of type stdClass as array in /data/web/virtuals/102175/virtual/www/domains/stred48.net/wp-content/plugins/skautis-integration/src/rules/Rule/Func.php:86 Stack trace: #0 /data/web/virtuals/102175/virtual/www/domains/stred48.net/wp-content/plugins/skautis-integration/src/rules/Rule/Func.php(142): SkautisIntegration\Rules\Rule\Func->getUserFuncsWithUnitIds() #1 /data/web/virtuals/102175/virtual/www/domains/stred48.net/wp-content/plugins/skautis-integration/src/rules/RulesManager.php(42): SkautisIntegration\Rules\Rule\Func->isRulePassed('in', '164~begins_with...') #2 /data/web/virtuals/102175/virtual/www/domains/stred48.net/wp-content/plugins/skautis-integration/src/rules/RulesManager.php(68): SkautisIntegration\Rules\RulesManager->processRule(Object(stdClass)) #3 /data/web/virtuals/102175/virtual/www/domains/stred48.net/wp-content/plugins/skautis-integration/src/rules/RulesManager.php(99): SkautisIntegration\Rules\RulesManager->parseRulesGroups('OR', Array) #4 /data/web/virtuals in /data/web/virtuals/102175/virtual/www/domains/stred48.net/wp-content/plugins/skautis-integration/src/rules/Rule/Func.php on line 86

**Comment by kalich5** [comment]
Špatně zadané pravidlo, kdy se ty podmínky vylučovaly.
