### ISSUE TITLE
Chyba (funkce) - Vedoucí střediska

### ISSUE THREAD

**Issue by kalich5** [skaut/skautis-integration#63]
[19-Mar-2018 21:44:33 UTC] PHP Fatal error: Uncaught Error: Cannot use object of type stdClass as array in /home/vu008538/www/wp-content/plugins/skautis-integration/src/rules/Rule/Func.php:86

8 Stack trace:

9 #0 /home/vu008538/www/wp-content/plugins/skautis-integration/src/rules/Rule/Func.php(149): SkautisIntegration\Rules\Rule\Func->getUserFuncsWithUnitIds()

10 #1 /home/vu008538/www/wp-content/plugins/skautis-integration/src/rules/RulesManager.php(43): SkautisIntegration\Rules\Rule\Func->isRulePassed('in', '5,158~equal~112...')

11 #2 /home/vu008538/www/wp-content/plugins/skautis-integration/src/rules/RulesManager.php(62): SkautisIntegration\Rules\RulesManager->processRule(Object(stdClass))

12 #3 /home/vu008538/www/wp-content/plugins/skautis-integration/src/rules/RulesManager.php(100): SkautisIntegration\Rules\RulesManager->parseRulesGroups('AND', Array)

13 #4 /home/vu008538/www/wp-content/plugins/skautis-integration/src/modules/Register/Register.php(123): SkautisIntegration\Rules\RulesManager->checkIfUserPassedRulesAndGetHisRole()

14 #5 /home/vu008538/www/wp-content/plu in /home/vu008538/www/wp-content/plugins/skautis-integration/src/rules/Rule/Func.php on line 86

15 [19-Mar-2018 21:45:01 UTC] PHP Fatal error: Uncaught Error: Cannot use object of type stdClass as array in /home/vu008538/www/wp-content/plugins/skautis-integration/src/rules/Rule/Func.php:86

16 Stack trace:

17 #0 /home/vu008538/www/wp-content/plugins/skautis-integration/src/rules/Rule/Func.php(149): SkautisIntegration\Rules\Rule\Func->getUserFuncsWithUnitIds()

18 #1 /home/vu008538/www/wp-content/plugins/skautis-integration/src/rules/RulesManager.php(43): SkautisIntegration\Rules\Rule\Func->isRulePassed('in', '5,158~equal~112...')

19 #2 /home/vu008538/www/wp-content/plugins/skautis-integration/src/rules/RulesManager.php(62): SkautisIntegration\Rules\RulesManager->processRule(Object(stdClass))

20 #3 /home/vu008538/www/wp-content/plugins/skautis-integration/src/rules/RulesManager.php(100): SkautisIntegration\Rules\RulesManager->parseRulesGroups('AND', Array)

21 #4 /home/vu008538/www/wp-content/plugins/skautis-integration/src/modules/Register/Register.php(123): SkautisIntegration\Rules\RulesManager->checkIfUserPassedRulesAndGetHisRole()

22 #5 /home/vu008538/www/wp-content/plu in /home/vu008538/www/wp-content/plugins/skautis-integration/src/rules/Rule/Func.php on line 86

**Comment by kalich5** [comment]
pořád stejná chyba...

**Comment by kalich5** [comment]
15 #3 /home/vu008538/www/wp-content/plugins/skautis-integration/src/rules/RulesManager.php(102): SkautisIntegration\Rules\RulesManager->parseRulesGroups('AND', Array)

16 #4 /home/vu008538/www/wp-content/plugins/skautis-integration/src/modules/Register/Register.php(123): SkautisIntegration\Rules\RulesManager->checkIfUserPassedRulesAndGetHisRole()

17 #5 /home/vu008538/www/wp-content/plu in /home/vu008538/www/wp-content/plugins/skautis-integration/src/rules/Rule/Func.php on line 86

18 [21-Mar-2018 22:01:54 UTC] PHP Notice: Undefined index: meta_theme_color in /home/vu008538/www/wp-content/plugins/chrome-on-android-meta-theme/chrome-meta-theme.php on line 18

19 [21-Mar-2018 22:02:05 UTC] PHP Fatal error: Uncaught Error: Cannot use object of type stdClass as array in /home/vu008538/www/wp-content/plugins/skautis-integration/src/rules/Rule/Func.php:86

20 Stack trace:

21 #0 /home/vu008538/www/wp-content/plugins/skautis-integration/src/rules/Rule/Func.php(149): SkautisIntegration\Rules\Rule\Func->getUserFuncsWithUnitIds()

22 #1 /home/vu008538/www/wp-content/plugins/skautis-integration/src/rules/RulesManager.php(45): SkautisIntegration\Rules\Rule\Func->isRulePassed('in', '5,158~equal~112...')

23 #2 /home/vu008538/www/wp-content/plugins/skautis-integration/src/rules/RulesManager.php(64): SkautisIntegration\Rules\RulesManager->processRule(Object(stdClass))

24 #3 /home/vu008538/www/wp-content/plugins/skautis-integration/src/rules/RulesManager.php(102): SkautisIntegration\Rules\RulesManager->parseRulesGroups('AND', Array)

25 #4 /home/vu008538/www/wp-content/plugins/skautis-integration/src/modules/Register/Register.php(123): SkautisIntegration\Rules\RulesManager->checkIfUserPassedRulesAndGetHisRole()

26 #5 /home/vu008538/www/wp-content/plu in /home/vu008538/www/wp-content/plugins/skautis-integration/src/rules/Rule/Func.php on line 86

**Comment by kalich5** [comment]
1 [21-Mar-2018 22:23:49 UTC] PHP Fatal error: Uncaught Error: Cannot use object of type stdClass as array in /home/vu008538/www/wp-content/plugins/skautis-integration/src/rules/Rule/Func.php:86

2 Stack trace:

3 #0 /home/vu008538/www/wp-content/plugins/skautis-integration/src/rules/Rule/Func.php(149): SkautisIntegration\Rules\Rule\Func->getUserFuncsWithUnitIds()

4 #1 /home/vu008538/www/wp-content/plugins/skautis-integration/src/rules/RulesManager.php(45): SkautisIntegration\Rules\Rule\Func->isRulePassed('in', '5,158~equal~112...')

5 #2 /home/vu008538/www/wp-content/plugins/skautis-integration/src/rules/RulesManager.php(64): SkautisIntegration\Rules\RulesManager->processRule(Object(stdClass))

6 #3 /home/vu008538/www/wp-content/plugins/skautis-integration/src/rules/RulesManager.php(102): SkautisIntegration\Rules\RulesManager->parseRulesGroups('AND', Array)

7 #4 /home/vu008538/www/wp-content/plugins/skautis-integration/src/modules/Register/Register.php(123): SkautisIntegration\Rules\RulesManager->checkIfUserPassedRulesAndGetHisRole()

8 #5 /home/vu008538/www/wp-content/plu in /home/vu008538/www/wp-content/plugins/skautis-integration/src/rules/Rule/Func.php on line 86
