### ISSUE TITLE
Chyba (funkce) - Zástupce vedoucího oddílu

### ISSUE THREAD

**Issue by kalich5** [skaut/skautis-integration#64]
1 [21-Mar-2018 21:57:28 UTC] PHP Fatal error: Uncaught Error: Cannot use object of type stdClass as array in /home/vu008538/www/wp-content/plugins/skautis-integration/src/rules/Rule/Func.php:86

2 Stack trace:

3 #0 /home/vu008538/www/wp-content/plugins/skautis-integration/src/rules/Rule/Func.php(149): SkautisIntegration\Rules\Rule\Func->getUserFuncsWithUnitIds()

4 #1 /home/vu008538/www/wp-content/plugins/skautis-integration/src/rules/RulesManager.php(45): SkautisIntegration\Rules\Rule\Func->isRulePassed('in', '5,158~equal~112...')

5 #2 /home/vu008538/www/wp-content/plugins/skautis-integration/src/rules/RulesManager.php(64): SkautisIntegration\Rules\RulesManager->processRule(Object(stdClass))

6 #3 /home/vu008538/www/wp-content/plugins/skautis-integration/src/rules/RulesManager.php(102): SkautisIntegration\Rules\RulesManager->parseRulesGroups('AND', Array)

7 #4 /home/vu008538/www/wp-content/plugins/skautis-integration/src/modules/Register/Register.php(123): SkautisIntegration\Rules\RulesManager->checkIfUserPassedRulesAndGetHisRole()

8 #5 /home/vu008538/www/wp-content/plu in /home/vu008538/www/wp-content/plugins/skautis-integration/src/rules/Rule/Func.php on line 86

**Comment by kalich5** [comment]
skončí to bílou obrazovkou

**Comment by kalich5** [comment]
Tak tento problém už není.
